# Site settings
title: Deutschland
client:
  name: Von der Nordsee bis zu den Alpen
  link: ""
core-se-link: https://www.secretescapes.de/aktuelle-angebote?utm_source=SE&utm_medium=hub&utm_campaign=australia_DE_2019
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=australia_DE_2019"
description: >
  Das Reiseland Deutschland hat viel mehr zu bieten als Fu√üball, Currywurst oder das Oktoberfest. Entdecken Sie unser Land ganz neu, abseits der Klischees und in all seiner Vielfalt.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/at/deutschland" # the subpath of your site, e.g. /blog/
img:     "/at/deutschland/_assets/img"
css:     "/at/deutschland/_assets/css"
js:      "/at/deutschland/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
